# Generated by Django 6.0.7 on 2026-07-16 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_researchcase_exact_context_and_custody'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_fingerprint', models.CharField(max_length=64)),
                ('reviewer_scope_snapshot', models.JSONField()),
                ('packet_digest_snapshot', models.CharField(max_length=64)),
                ('rubric_digest_snapshot', models.CharField(max_length=64)),
                ('subject_mode_snapshot', models.CharField(max_length=32)),
                ('decision', models.CharField(choices=[('licensed', 'Licensed'), ('requires_narrowing', 'Requires narrowing'), ('reject', 'Reject'), ('ambiguous', 'Ambiguous')], max_length=32)),
                ('rationale', models.TextField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='first_pass', to='review.queueassignment')),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExposureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_digest', models.CharField(max_length=64)),
                ('exposed_at', models.DateTimeField(auto_now_add=True)),
                ('first_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exposure', to='review.firstpass')),
            ],
        ),
        migrations.CreateModel(
            name='LineageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('role', 'Agent role'), ('prompt', 'Prompt'), ('skill', 'Skill'), ('tool', 'Tool trace'), ('source', 'Source use'), ('artifact', 'Artifact evolution'), ('claim_transition', 'Claim transition'), ('synthesis', 'Synthesis use'), ('machine_judgment', 'Machine judgment')], max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('exact', 'Exact captured record'), ('missing', 'Missing'), ('redacted', 'Redacted'), ('digest_only', 'Digest only')], max_length=16)),
                ('locator', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('content_digest', models.CharField(blank=True, max_length=64)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineage_records', to='review.researchcase')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('case', 'sequence'), name='lineage_sequence_per_case')],
            },
        ),
    ]
