# Generated by Django 6.0.7 on 2026-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_firstpass_exposureevent_lineagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposureevent',
            name='lineage_snapshot',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='firstpass',
            name='packet_snapshot',
            field=models.JSONField(default=dict, editable=False),
        ),
    ]
