# Generated by Django 6.0.7 on 2026-07-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_assignment_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_fingerprint', models.CharField(max_length=64)),
                ('adjudicated_decision', models.CharField(choices=[('licensed', 'Licensed'), ('requires_narrowing', 'Requires narrowing'), ('reject', 'Reject'), ('ambiguous', 'Ambiguous')], max_length=32)),
                ('diagnosis', models.TextField()),
                ('corrected_judgment', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('first_pass', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion', to='review.firstpass')),
            ],
        ),
        migrations.CreateModel(
            name='FutureProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(max_length=24)),
                ('proposed_change', models.TextField()),
                ('reversibility_plan', models.TextField()),
                ('status', models.CharField(default='inactive_quarantined', editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='future_proposal', to='review.reviewcompletion')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrected_state', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='current_correction', to='review.reviewcompletion')),
            ],
        ),
        migrations.CreateModel(
            name='RubricEvalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_type', models.CharField(max_length=32)),
                ('proposed_state', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_eval_state', to='review.reviewcompletion')),
            ],
        ),
        migrations.CreateModel(
            name='ConsequenceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=48)),
                ('target', models.CharField(max_length=48)),
                ('rationale', models.TextField()),
                ('payload', models.TextField(blank=True)),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='review.reviewcompletion')),
            ],
            options={
                'ordering': ('family',),
                'constraints': [models.UniqueConstraint(fields=('completion', 'family'), name='one_decision_per_consequence_family')],
            },
        ),
    ]
