# Generated by Django 6.0.7 on 2026-07-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_append_only_completion_history'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consequencedecision',
            constraint=models.CheckConstraint(condition=models.Q(('pk__isnull', True), models.Q(('action', 'apply_current_correction'), ('family', 'current'), ('target', 'current_report_state')), models.Q(('action', 'reject_current_correction'), ('family', 'current'), ('target', 'review_record')), models.Q(('action', 'defer_current_correction'), ('family', 'current'), ('target', 'current_deferred_queue')), models.Q(('action', 'absent_current_correction'), ('family', 'current'), ('target', 'no_target')), models.Q(('action', 'create_rubric_precedent'), ('family', 'rubric'), ('target', 'rubric_precedent_pool')), models.Q(('action', 'create_eval_candidate'), ('family', 'rubric'), ('target', 'protected_eval_candidate_pool')), models.Q(('action', 'reject_rubric_or_eval'), ('family', 'rubric'), ('target', 'review_record')), models.Q(('action', 'defer_rubric_or_eval'), ('family', 'rubric'), ('target', 'rubric_eval_deferred_queue')), models.Q(('action', 'absent_rubric_or_eval'), ('family', 'rubric'), ('target', 'no_target')), models.Q(('action', 'propose_prompt_change'), ('family', 'future'), ('target', 'future_proposal_quarantine')), models.Q(('action', 'propose_retrieval_change'), ('family', 'future'), ('target', 'future_proposal_quarantine')), models.Q(('action', 'propose_workflow_change'), ('family', 'future'), ('target', 'future_proposal_quarantine')), models.Q(('action', 'reject_future_change'), ('family', 'future'), ('target', 'review_record')), models.Q(('action', 'defer_future_change'), ('family', 'future'), ('target', 'future_deferred_queue')), models.Q(('action', 'absent_future_change'), ('family', 'future'), ('target', 'no_target')), _connector='OR'), name='legal_consequence_action_target'),
        ),
        migrations.AddConstraint(
            model_name='futureproposal',
            constraint=models.CheckConstraint(condition=models.Q(('intervention_type__in', ('prompt', 'retrieval', 'workflow'))), name='legal_future_intervention_type'),
        ),
        migrations.AddConstraint(
            model_name='futureproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'inactive_quarantined')), name='future_proposal_never_activates_itself'),
        ),
        migrations.AddConstraint(
            model_name='rubricevalstate',
            constraint=models.CheckConstraint(condition=models.Q(('state_type__in', ('rubric', 'eval'))), name='legal_rubric_eval_state_type'),
        ),
    ]
