# Generated by Django 6.0.7 on 2026-07-23 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_atomic_population_admission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='populationadmission',
            name='one_admission_idempotency_key_per_enrollment',
        ),
        migrations.AddField(
            model_name='populationadmission',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='population_admission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='populationadmission',
            name='idempotency_key',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.RemoveField(
            model_name='populationadmission',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='lineagerecord',
            name='span_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='lineagerecord',
            name='trace_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
    ]
