# Generated by Django 6.0.7 on 2026-07-23 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(choices=[('planner', 'Planner'), ('director', 'Research director'), ('researcher', 'Research worker'), ('reviewer', 'Adversarial reviewer')], max_length=16)),
                ('protocol', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=240)),
                ('task', models.TextField()),
                ('contract', models.JSONField(default=dict, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_proposals', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='campaign.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision requested')], max_length=24)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='campaign.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('issuer_or_security', models.CharField(max_length=240)),
                ('equities_decision_use', models.TextField()),
                ('evidence_cutoff', models.DateField()),
                ('commissioned_question', models.TextField()),
                ('ntm_session', models.CharField(editable=False, max_length=80, unique=True)),
                ('artifact_root', models.TextField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='campaign.researchcampaign'),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=80)),
                ('relative_path', models.TextField()),
                ('version', models.PositiveIntegerField()),
                ('media_type', models.CharField(max_length=120)),
                ('content', models.BinaryField()),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='campaign.researchcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logical_role_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('protocol', models.CharField(max_length=80)),
                ('proposal_digest', models.CharField(editable=False, max_length=64)),
                ('input_artifact_ids', models.JSONField(default=list, editable=False)),
                ('packet', models.JSONField(default=dict, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='campaign.researchcampaign')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='campaign.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(max_length=64)),
                ('observation_id', models.CharField(max_length=64)),
                ('conversation_id', models.CharField(max_length=160)),
                ('call_id', models.CharField(max_length=160)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trace_link', to='campaign.artifact')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_links', to='campaign.researchcampaign')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_links', to='campaign.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('launch', 'Launch capacity'), ('status', 'Observe readiness'), ('send', 'Send exact work order'), ('stop', 'Stop campaign runtime'), ('readback', 'Read back Langfuse observations')], max_length=16)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('request', models.JSONField(default=dict, editable=False)),
                ('response', models.JSONField(editable=False, null=True)),
                ('succeeded', models.BooleanField(default=False, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_events', to='campaign.researchcampaign')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_events', to='campaign.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artifact',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='campaign.workorder'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(fields=('work_order', 'relative_path', 'version'), name='lean_artifact_path_version'),
        ),
    ]
