# Generated by Django 6.0.7 on 2026-08-03 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_lean_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='state_basis',
            field=models.CharField(choices=[('commission', 'Commission'), ('accepted_transition', 'Accepted research state'), ('challenged_transition', 'Challenged research state')], default='commission', max_length=24),
        ),
        migrations.CreateModel(
            name='ResearchStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_transitions', to='campaign.researchcampaign')),
                ('delta_artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='epistemic_delta', to='campaign.artifact')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='campaign.researchstatetransition')),
                ('state_artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_state', to='campaign.artifact')),
                ('workbench_artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='research_workbench_result', to='campaign.artifact')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='state_transition', to='campaign.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchStateDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accepted', 'Accepted'), ('challenged', 'Challenge and route back'), ('rejected', 'Rejected')], max_length=16)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposition', to='campaign.researchstatetransition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='input_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependent_work_orders', to='campaign.researchstatetransition'),
        ),
    ]
