# Generated by Django 6.0.7 on 2026-08-14 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_workorder_state_basis_researchstatetransition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("starting_artifact", "Starting artifact"), ("source", "Source")], max_length=32)),
                ("filename", models.CharField(max_length=240)),
                ("media_type", models.CharField(max_length=120)),
                ("content", models.BinaryField()),
                ("digest", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="input_artifacts", to="campaign.researchcampaign")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RunSpecVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("objective", models.TextField()),
                ("instruction", models.TextField()),
                ("input_manifest", models.JSONField(default=list, editable=False)),
                ("outcome_contract", models.JSONField(default=dict, editable=False)),
                ("digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("campaign", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="run_spec", to="campaign.researchcampaign")),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="workorder",
            name="run_spec",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="campaign.runspecversion"),
        ),
    ]
