# Generated by Django 6.0.7 on 2026-08-17 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_bound_input_history_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissibilityDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('validator_version', models.CharField(max_length=80)),
                ('outcome', models.CharField(choices=[('PASS', 'Pass'), ('BLOCK', 'Block'), ('UNSUPPORTED', 'Unsupported'), ('JUDGMENT_REQUIRED', 'Judgment required')], max_length=24)),
                ('reason_code', models.CharField(max_length=80)),
                ('closure_digest', models.CharField(editable=False, max_length=64)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceAssertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locator', models.TextField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('unit', models.CharField(max_length=40)),
                ('dimensions', models.JSONField(default=dict, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_children', to='campaign.artifactversion'),
        ),
        migrations.AlterField(
            model_name='artifactversion',
            name='role',
            field=models.CharField(choices=[('starting_artifact', 'Starting artifact'), ('source', 'Source'), ('candidate', 'Candidate')], max_length=32),
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='candidate_from_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_artifacts', to='campaign.admissibilitydecision'),
        ),
        migrations.CreateModel(
            name='ArtifactManifestVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_profile', models.CharField(max_length=120)),
                ('adapter_version', models.CharField(max_length=80)),
                ('target_ref', models.CharField(max_length=160)),
                ('target_address', models.CharField(max_length=160)),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('target_unit', models.CharField(max_length=40)),
                ('allowed_operation', models.CharField(max_length=80)),
                ('dependency_closure', models.JSONField(default=list, editable=False)),
                ('formula_bindings', models.JSONField(default=dict, editable=False)),
                ('inspection_digest', models.CharField(editable=False, max_length=64)),
                ('support_status', models.CharField(choices=[('SUPPORTED', 'Supported'), ('UNSUPPORTED_PROFILE', 'Unsupported profile'), ('UNSUPPORTED_STRUCTURAL_OPERATION', 'Unsupported structural operation')], default='SUPPORTED', max_length=40)),
                ('warnings', models.JSONField(default=list, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_manifests', to='campaign.artifactversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelChangeEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('named_use', models.TextField()),
                ('cutoff', models.DateField()),
                ('input_revision', models.PositiveIntegerField(default=1)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_episode', to='campaign.researchcampaign')),
                ('starting_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_model_change_episodes', to='campaign.artifactversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptualObjectVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binding_status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('PROPOSED_STRUCTURE', 'Proposed structure')], max_length=32)),
                ('economic_meaning', models.JSONField(default=dict, editable=False)),
                ('method_policy', models.JSONField(default=dict, editable=False)),
                ('claim_ceiling', models.TextField()),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manifest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conceptual_objects', to='campaign.artifactmanifestversion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_objects', to='campaign.conceptualobjectversion')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptual_objects', to='campaign.modelchangeepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_version', models.CharField(max_length=80)),
                ('adapter_profile', models.CharField(max_length=120)),
                ('engine_identity', models.CharField(max_length=240)),
                ('engine_version', models.CharField(max_length=240)),
                ('timeout_seconds', models.PositiveIntegerField()),
                ('environment', models.JSONField(default=dict, editable=False)),
                ('operation_receipt', models.JSONField(default=dict, editable=False)),
                ('input_digest', models.CharField(editable=False, max_length=64)),
                ('output_digest', models.CharField(editable=False, max_length=64)),
                ('consequences', models.JSONField(default=list, editable=False)),
                ('warnings', models.JSONField(default=list, editable=False)),
                ('formula_errors', models.JSONField(default=list, editable=False)),
                ('closure_digest', models.CharField(editable=False, max_length=64)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_receipt', to='campaign.artifactversion')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_receipts', to='campaign.artifactmanifestversion')),
                ('pass_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_receipt', to='campaign.admissibilitydecision')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_receipts', to='campaign.modelchangeepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='artifactmanifestversion',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_manifests', to='campaign.modelchangeepisode'),
        ),
        migrations.CreateModel(
            name='ArtifactDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('named_use', models.TextField()),
                ('kind', models.CharField(choices=[('SIMULATE_NAMED_USE', 'Simulate named use'), ('REJECT', 'Reject'), ('REWORK', 'Request rework')], max_length=24)),
                ('rationale', models.TextField(blank=True)),
                ('closure_digest', models.CharField(max_length=64)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_dispositions', to='campaign.artifactversion')),
                ('calculation_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_dispositions', to='campaign.calculationreceipt')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_dispositions', to='campaign.modelchangeepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('USE_FILED_ANNUAL_REPORT', 'Use filed annual report'), ('AMEND_MEANING', 'Amend meaning'), ('AMEND_METHOD_POLICY', 'Amend method policy'), ('AMEND_ASSUMPTION', 'Amend assumption')], max_length=40)),
                ('bounded_change', models.JSONField(default=dict, editable=False)),
                ('rationale', models.TextField()),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('blocked_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='campaign.admissibilitydecision')),
                ('object_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='campaign.conceptualobjectversion')),
                ('replacement_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_amendments', to='campaign.conceptualobjectversion')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='campaign.modelchangeepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelChangeProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposer_kind', models.CharField(choices=[('MODEL', 'Model'), ('HOST_DERIVED', 'Host-derived replacement')], max_length=20)),
                ('input_revision', models.PositiveIntegerField()),
                ('operation', models.JSONField(default=dict, editable=False)),
                ('protocol_version', models.CharField(max_length=80)),
                ('claim_ceiling', models.TextField()),
                ('closure_digest', models.CharField(editable=False, max_length=64)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conceptual_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.conceptualobjectversion')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.modelchangeepisode')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.artifactmanifestversion')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_proposals', to='campaign.modelchangeproposal')),
                ('starting_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.artifactversion')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.workorder')),
                ('source_assertion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_proposals', to='campaign.sourceassertion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_assertions', models.JSONField(default=list, editable=False)),
                ('protocol_version', models.CharField(max_length=80)),
                ('adapter_profile_version', models.CharField(max_length=160)),
                ('reason_code', models.CharField(max_length=80)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amendment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='correction_record', to='campaign.amendment')),
                ('blocked_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_records', to='campaign.admissibilitydecision')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_records', to='campaign.artifactversion')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_records', to='campaign.modelchangeepisode')),
                ('replacement_proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_records', to='campaign.modelchangeproposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='amendment',
            name='replacement_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_amendments', to='campaign.modelchangeproposal'),
        ),
        migrations.AddField(
            model_name='admissibilitydecision',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admissibility_decision', to='campaign.modelchangeproposal'),
        ),
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_ref', models.CharField(max_length=240)),
                ('mandate_ref', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modelchangeepisode',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_change_episodes', to='campaign.researchjob'),
        ),
        migrations.CreateModel(
            name='SourceDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_class', models.CharField(choices=[('EARNINGS_RELEASE_8K', '8-K earnings release'), ('FILED_ANNUAL_REPORT_10K', 'Filed annual report')], max_length=40)),
                ('identity', models.JSONField(default=dict, editable=False)),
                ('access_context', models.JSONField(default=dict, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source_document', to='campaign.artifactversion')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='campaign.modelchangeepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sourceassertion',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assertions', to='campaign.sourcedocumentversion'),
        ),
        migrations.CreateModel(
            name='InvalidationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descendant_type', models.CharField(choices=[('OBJECT', 'Conceptual object'), ('PROPOSAL', 'Proposal'), ('DECISION', 'Decision'), ('CANDIDATE', 'Candidate'), ('CALCULATION', 'Calculation receipt'), ('DISPOSITION', 'Artifact disposition')], max_length=24)),
                ('descendant_id', models.UUIDField()),
                ('descendant_digest', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=120)),
                ('closure_digest', models.CharField(max_length=64)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amendment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidation_events', to='campaign.amendment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('amendment', 'descendant_type', 'descendant_id'), name='model_change_invalidation_once')],
            },
        ),
        migrations.CreateModel(
            name='ObjectDisposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CONFIRM_MEANING', 'Confirm meaning'), ('AMEND_MEANING', 'Amend meaning'), ('AUTHORIZE_METHOD', 'Authorise method')], max_length=32)),
                ('bounded_payload', models.JSONField(default=dict, editable=False)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('object_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_dispositions', to='campaign.conceptualobjectversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('object_version', 'action'), name='model_change_object_disposition_once')],
            },
        ),
    ]
